---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: springboot
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: spring-app
          image: srinubabuthammisetti/myspringboot:1.0
          ports:
            - containerPort: 80



